# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/work/CPUDesignandVerification/250522_SPI_M_S/.Xil/Vivado-26628-DESKTOP-7CFQ9ND/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a35tcpg236-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/d0f7
    c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/ec67/hdl
  } {
      C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/d0f7
    c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/ec67/hdl
  } {
      C:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.srcs/sources_1/new/SPI_Slave_intf.v
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/synth/design_1.v
      C:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v
    }
      rt::read_verilog -include {
    c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/d0f7
    c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/ec67/hdl
  } {
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/05b2/hdl/myip_axi_spi_m_v1_0_S00_AXI.v
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/05b2/hdl/myip_axi_spi_m_v1_0.v
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ip/design_1_myip_axi_spi_m_0_2/synth/design_1_myip_axi_spi_m_0_2.v
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_clk_wiz.v
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.v
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/54c0/hdl/axi_data_fifo_v2_1_vl_rfs.v
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/bc0a/hdl/axi_crossbar_v2_1_vl_rfs.v
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ip/design_1_xbar_0/synth/design_1_xbar_0.v
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ip/design_1_SPI_Slave_0_0/synth/design_1_SPI_Slave_0_0.v
    }
      rt::read_vhdl -lib microblaze_v11_0_4 c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/9285/hdl/microblaze_v11_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ip/design_1_microblaze_0_0/synth/design_1_microblaze_0_0.vhd
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/synth/design_1_dlmb_v10_0.vhd
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/synth/design_1_ilmb_v10_0.vhd
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/synth/design_1_dlmb_bram_if_cntlr_0.vhd
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0/synth/design_1_ilmb_bram_if_cntlr_0.vhd
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ip/design_1_lmb_bram_0/synth/design_1_lmb_bram_0.vhd
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ip/design_1_mdm_1_0/synth/design_1_mdm_1_0.vhd
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/synth/design_1_rst_clk_wiz_1_100M_0.vhd
      c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/synth/design_1_axi_uartlite_0_0.vhd
    }
      rt::read_vhdl -lib lmb_v10_v3_0_11 c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/c2ed/hdl/lmb_v10_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib lmb_bram_if_cntlr_v4_0_19 c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/0b98/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_4 c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/2985/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib axi_lite_ipif_v3_0_4 c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib mdm_v3_2_19 c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/8715/hdl/mdm_v3_2_vh_rfs.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_2 c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_13 c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_5 c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/276e/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib lib_pkg_v1_0_2 c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_srl_fifo_v1_0_2 c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib axi_uartlite_v2_0_26 c:/work/CPUDesignandVerification/250522_SPI_M_S/250522_SPI_M_S.gen/sources_1/bd/design_1/ipshared/5edb/hdl/axi_uartlite_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top design_1_wrapper
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/work/CPUDesignandVerification/250522_SPI_M_S/.Xil/Vivado-26628-DESKTOP-7CFQ9ND/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
